appFive/urls.py
from django.urls import path,re_path
from appFive import views

app_name = "appFive"
urlpatterns = [
    re_path(r'^register',views.register,name='register'),
]

appFour/urls.py
from django.urls import path, re_path
from appFour import views

app_name = "appFour"
urlpatterns = [
    re_path(r'^index/$',views.index,name='index'),
    re_path(r'^page1/$',views.page1,name='page1'),
    re_path(r'^page2/$',views.page2,name='page2')
]

first_app/urls.py
from django.urls import path,re_path
from first_app import views

urlpatterns = [
    path(r'users',views.index,name='user'),
    path(r'form',views.create_user,name='form'),

]

first_project/urls.py
from django.contrib import admin
from django.urls import path,re_path,include

from appFour import views

urlpatterns = [
    #re_path(r'^$',views.index,name='index'),
    re_path(r'^first_app/',include('first_app.urls')),
    path('admin/', admin.site.urls),
    re_path(r'^appFour',include('appFour.urls')),
    path('',views.index),
    re_path(r'^appFive/',include('appFive.urls'))

]

appFive/models.py
from django.db import models

# Create your models here.
class UserInfoApp(models.Model):
    user = models.CharField(max_length=264)
    email = models.CharField(max_length=264,unique=True)
    password = models.CharField(max_length=264)

    def __str__(self):
        return self.user

class UserProfileInfoApp(models.Model):
    user_info = models.OneToOneField(UserInfoApp, on_delete=models.CASCADE)
    #additional
    profile_site_app = models.URLField(blank=True)
    profile_pic_app  = models.ImageField(upload_to='profile_pic_app',blank=True)

    def __str__(self):
        return self.user_info.email
    

appFour/models.py
from django.db import models

# Create your models here.

first_app/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    first_name = models.CharField(max_length=264)
    last_name = models.CharField(max_length=264)
    email = models.CharField(max_length=264,unique=True)

    def __str__(self):
        return self.email

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    #additional
    profile_site = models.URLField(blank=True)
    profile_pic  = models.ImageField(upload_to='profile_pic',blank=True)

    def __str__(self):
        return self.user.email
    

appFive/views.py
from django.shortcuts import render,redirect
from appFive.models import UserInfoApp,UserProfileInfoApp
from django.contrib.auth.models import User
from . import form
# Create your views here.
def register(request):
    registered = False
    if request.method == "POST":
        user_form = form.UserInfoAppForm(data=request.POST)
        profile_form = form.UserProfileFormAppForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            userinfo = user_form.save(commit=False)
            user = User.objects.create_user(username=userinfo.user,password=userinfo.password)
            userinfo.user = user
            userinfo.save()

            profile = profile_form.save(commit=False)
            profile.user_info = userinfo

            if 'profile_pic_app' in request.FILES:
                profile.profile_pic_app = request.FILES['profile_pic_app']
            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = form.UserInfoAppForm()
        profile_form = form.UserProfileFormAppForm()

    return render(request, 'appFive/registration.html', {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})

appFour/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'appFour/index.html',{'text':'Hello world','number':100})
def page1(request):
    return render(request,'appFour/page1.html',{'text1':"Đây là Page 1",'number1':100})
def page2(request):
    return render(request,'appFour/page2.html',{'text2':"Đây là Page 2",'number2':50})

first_app/views.py
from django.shortcuts import render,redirect
from first_app.models import User,UserProfileInfo
from . import form
# Create your views here.
#Tạo user 
def create_user(request):
    myForm = form.FormName()
    if request.method == "POST":
        myForm = form.FormName(request.POST)
        if myForm.is_valid():
            user = myForm.save()
            return redirect('/first_app/users')

    return render(request,'basic_app/form.html',{'form':myForm})

def index(request):
    list = User.objects.values()
    list_user = {'user_list': list}
    return render(request,'index.html',context=list_user)

def form_name_view(request):
    myForm = form.FormName()

    if request.method == 'POST':
        myForm = form.FormName(request.POST)
        
        if myForm.is_valid():
            print("Validation success")
            print("Name: "+myForm.cleaned_data['name'])
            print("Email: "+myForm.cleaned_data['email'])
            print("Text: "+myForm.cleaned_data['text'])
        else:
            print("zzz")

    return render(request, 'basic_app/form.html',{'form':myForm})



   

templates/appFive/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <title>Home</title>
</head>
<body>
   <nav class = "navbar navbar-expand-md navbar-light bg-light">
        <div class="container">
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class ="navbar-nav me-auto">
                    <li class ="nav-item"><a class="navbar-brand" href="{% url 'admin:index' %}">DJANGO</a></li>
                    <li class ="nav-item"><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                    <li class ="nav-item"><a class="navbar-link" href="{% url 'appFive:register' %}">Register</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        {% block body_block %}
        {% endblock %}
</body>         
</html>

templates/appFive/index.html
{% extends 'appFive/base.html' %}
{% block body_block %}
    <div class="mt-4 p-5 bg-light rounded">
        <h1>Django Level Five </h1>
    </div>
{% endblock %}

templates/appFive/registration.html
{% extends 'appFive/base.html' %}
{% load static %}
{% block body_block %}
    <div class="mt-4 p-5 bg-light rounded">
        {% if registered %}
            <h1>Thank you for registering !! </h1>
        {% else %}
            <h1>Register here !! </h1>
            <h3>Fill out the form: </h3>
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ user_form.as_p }}
                {{ profile_form.as_p }}
                <input type="submit" value ="Register" class="btn btn-info">
            </form>
        {% endif %}
    </div>
{%endblock%}

templates/appFour/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <title>Home</title>
</head>
<body>
   <h1>Welcome to Relative URL Template</h1>
   <ul>
        <li><a href = "{% url 'appFour:index' %}">Home</a></li>
        <li><a href = "{% url 'appFour:page1' %}">Page1</a></li>
        <li><a href = "{% url 'appFour:page2' %}">Page2</a></li>
   </ul>
   <div class = "container">
    {% block body_block %}
        
    {% endblock %}
    </div>
</body>
</html>

templates/appFour/index.html
{% extends "appFour/base.html" %}
{% block body_block %}
    <h1>This is home</h1>
    {{ text }}
    {{ number }}
{% endblock %}

templates/appFour/page1.html
{% extends "appFour/base.html" %}
{%block body_block%}
    {{ text1 }}
    {{ number1|add:"99" }}
{%endblock%}

templates/appFour/page2.html
{% extends "appFour/base.html" %}
{%block body_block%}
    {{ text2 }}
    {{ number2|add:"50" }}
{%endblock%}

templates/basic_app/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <title>Home</title>
</head>
<body>
   
   <div class = "container">
    <h1>Sign in</h1>
        <form method = "POST">
            {{ form.as_p }}
            {% csrf_token %}
            <button type ="submit" class="btn-success">Sign in</button>
        </form>
   </div>
</body>
</html>

templates/basic_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/styles.css'%}">
    <title>Home</title>
</head>
<body>
   <h1>Welcome to home page</h1>
   <h2>Go to /formpage to fill out the form </h2>
</body>
</html>

templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/styles.css'%}">
    <title>Fisrt App</title>
</head>
<body>
    <h1>Hi this is django level two</h1>
    
    {% if user_list %}
    <table border="3">
        <thead>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
        </thead>
        {% for user in user_list %}
        <tr>
            <td>{{ user.first_name }}</td>
            <td>{{ user.last_name }}</td>
            <td>{{ user.email }}</td>
        </tr>
        {% endfor %}
</table>
    {% else %}
    <p>NO ACCES RECORD FOUND !</p>
    {% endif %}
</body>
</html>